### ISSUE TITLE
Would you mind uploading the corner tracking algorithm code?

### ISSUE THREAD

**Issue by yuanliang861** [ialzugaray/arc_star_ros#1]
Thank you for your excelent work. This repository did not include the tracking algorithm code. Would you mind uploading the corner tracking algorithm code?

**Comment by ialzugaray** [comment]
Hi Yuan,
I am currently working on other projects and thus I do not think I will work on the release the corner tracking algorithm of this specific paper in the following months.  However, I encourage you to check our more recent works presented at 3DV 2018 and 3DV 2019 that propose a couple of more reliable approaches to feature tracking with event cameras.

Best,
Ignacio
