### ISSUE TITLE
Asynchronous corner tracker

### ISSUE THREAD

**Issue by BoogaardR** [ialzugaray/arc_star_ros#2]
Hi, thank you for sharing the algorithm. I wonder if it would be possible to share the ‘tracker’ described in your paper as well.
Thanks you in advance

**Comment by ialzugaray** [comment]
Dear @BoogaardR,
Unfortunately, the naive "tracker" I described in the paper will not be released, but its re-implementation should be straightforward (simple NN + graph creation and branch selection). An improved version of such a tracker (much better stability and track retrival mechanism) is described in "ACE: An efficient asynchronous corner tracker for event cameras" but the code is also not published.

Nonetheless, we encourage you to take a look at our lastest publications on feature tracking for event cameras which have efficient public implementations for benchmarking: https://github.com/ialzugaray/haste

Best,
Ignacio

**Comment by BoogaardR** [comment]
Dear Ignacio,

Thank you for the quick response. I will take a look at the HASTE publications.
I do have a question related to the Arc publication. Is it possible to gather a output data file from the tracked corners? A collection of corner location over time?

Kind regards,
Rik van den Boogaard

**Comment by ialzugaray** [comment]
Unfortunately, I would have a hard time finding the original raw data for the data association/tracker of the Arc publication (it was published 5 years ago and it would probably be in a non-friendly parseable format) and I do not have currently the time to re-run the code and reproduce such results. In any case, if you want a tree-like data association strategy I would rather attempt to replicate the ACE tracker instead.

**Comment by BoogaardR** [comment]
Hi,

Thank you again for the quick response. I have one final question. I am doing my master thesis on comparing a Frame-based camera with an Event-based camera by tracking features from a rotating object (Scale Asteroid). Therefore, I would like to use your publication "Asynchronous multi-Hypothesis tracking of features with event camera.". I want to compare the tracked feature using their location and at specific time stamps. Do you think your HASTE publication is suitable for that? Is it possible to get information(position,pixel error) at different times from HASTE?

Kind regards,
Rik van den Boogaard

**Comment by ialzugaray** [comment]
That would depend on whether you can reliably create a patch-template of the features you are trying to track (similar to a traditional KLT tracker). Essentially whether the tracked features are rotating (hard) or whether the camera it is rotating (OK). In any case, feel free to reach me by email as this discussion is tangential to this specific repository.

**Comment by BoogaardR** [comment]
Hi,

To clarify. The event camera will be stationary while the object to observe is rotating. I am using a KLT tracker for the traditional camera and want to recreate similar output as a KLT tracker for the Event camera (Prophesee Gen 3.1). In that way, I want to compare the tracking error of the two cameras under different illuminating and object rotation conditions.
Do you think using HASTE would give me an output that I can use/compare to the traditional KLT tracker?

I really appreciate your help.

Kind regards,
Rik
